# Site wide configuration

title:            Random Inferences
locale:           en_US
url:              http://jverma.github.io/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Janu Verma
  avatar: 
  bio: "Research Engineer at IBM T.J. Watson Research Center."
  email:
  disqus-shortname:
  twitter: @januverma
  facebook: janu.verma
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Jverma
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: janu-verma-b79b8823
  xing: #username
  instagram: jverma
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  quora: Janu-Verma-2

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
